### PR TITLE
Update to DQL on SDK 4.5.1

### PR DESCRIPTION
**Pull request by kndoshn**

### CODE REVIEW

**Comment by kndoshn** [comment]
This is ready for review.

**Comment by zmarkan** [comment]
I'll have a look this week - but need to first check out the whole codebase to understand what I'm looking at

**Comment by magicwave** [comment]
Zan and I are going to pair to review the PR on Thur, June 13

**Review by zmarkan — CHANGES_REQUESTED** [review]
Went through the code with @magicwave yesterday. Everything works fine but we noticed it's not 100% like for like with the swift template app.

Here are the main differences with iOS app - https://github.com/getditto/template-app-swift-todo:

- Naming - `isDeleted` here should be changed to `isSafeForEviction` to be in line with best practices & the swift template - **needs updating before merging**
- There is no concept of 'invitations' and 'userIds' in the Android app. Should we have it across both? Not required for this PR.
- This app triggers eviction on startup where iOS doesn't currently handle it


Additional remarks:
- The SDK used is 4.5.1 - **needs updating before merging** 
- The codebase needs more comments. - OK to merge but needs a separate issue.

**Comment by zmarkan** [comment]
Happy to pick up the requested changes & then we can review again @magicwave ?

**Comment by okdistribute** [comment]
Thank you! I would say keep it simple, no need for invitations/users/evictions in this simple example

**Review by okdistribute — APPROVED** [review]

**Pull request merged**
